#!/bin/bash
# Basic System Hardening Script
# Generated by Linux Security Audit Tool

set -e
echo "Starting basic system hardening..."

# Update system
echo "Updating system packages..."
apt update && apt upgrade -y

# Enable UFW firewall
echo "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw --force enable

# Install security tools
echo "Installing security tools..."
apt install -y unattended-upgrades fail2ban auditd

# Configure automatic updates
echo "Configuring automatic updates..."
sed -i 's|//Unattended-Upgrade::Remove-Unused-Dependencies "false";|Unattended-Upgrade::Remove-Unused-Dependencies "true";|' /etc/apt/apt.conf.d/50unattended-upgrades

echo "Basic hardening completed!"
